### ISSUE TITLE
without summarize_dap2enloc.pl code 

### ISSUE THREAD

**Issue by zhoudreames** [songtaogui/pan-Zea_utilities#1]
Following your fine map methd,  I don't find this summarize_dap2enloc.pl script here, can you provide me? thanks~

**Comment by zhoudreames** [comment]
@songtaogui can you help me ? thanks~

**Comment by songtaogui** [comment]
@zhoudreames you could find the code here: https://github.com/xqwen/fastenloc/blob/master/src/summarize_dap2enloc.pl

**Comment by songtaogui** [comment]
@zhoudreames have you successfully got the code from the above url? 

I'll close this issue. Feel free to ask again for any questions.

Best wishes.

Songtao Gui
